config/routes.rb
Rails.application.routes.draw do
  
  get 'message/index'
  get 'message/send_form/:id'=> 'message#send_form'
  post 'message/create'
  delete 'message/destroy/:id' => 'message#destroy'
  
  get 'users/show'
  get 'users/messages'

  post 'interest/index' => 'interest#interest'
  
  post 'comment/create'
  delete 'comment/destroy/:id' => 'comment#destroy'

  
  resources :club
  resources :article
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  match 'users/:id' => 'users#show', via: :get
  
  
  root 'club#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :club
  belongs_to :user
  mount_uploaders :images, ArticleimagesUploader
  serialize :images, JSON
  has_many :comments, dependent: :delete_all
end

app/models/club.rb
class Club < ActiveRecord::Base
  mount_uploader :mainimage, MainimageUploader
  has_many :articles, dependent: :delete_all
  has_many :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/interest.rb
class Interest < ActiveRecord::Base
    belongs_to :user
    has_many :clubs
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :content, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :comments, dependent: :delete_all
  has_many :messages, dependent: :delete_all
  has_many :articles, dependent: :delete_all
  has_one :interest
  
  belongs_to :club
  
  validate :password_complexity
  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password, '특수문자와 숫자를 잊지 않으셨죠?!'
  end
end

#:confirmable

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
#디바이스젬 계정 보안
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
#스트롱 파라미터, 계정 보안  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :major, :student_id])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :major, :student_id])
  end
  
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to :back
  end

  def destroy
    if check_user == true

      @article.destroy
      redirect_to Club.find(@article.club_id)

    #로그인하지 않은 경우
    elsif current_user == nil
      #TODO: 로그인 후 이용해주세요 알람창 뜨게하기 자바스크립트로 해야함
      redirect_to 'users/sign-in'

    # 본인 댓글이 아닐경우
    else
      #TODO: 본인댓글만 삭제할 수 있습니다. 알람창 뜨게하기 자바스크립트로 해야함
      redirect_to :back
    end
  end

  def edit

  end

  def update
    @article.update(article_params)
    redirect_to Club.find(@article.club_id)
  end

  def new
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :club_id, :user_id, {images: []})
    end

    def check_user
      if User.find(@article.user_id) == current_user
        return true
      else
        return false
      end
    end
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]
  
  
  def index
    @clubs = Club.all
  end

  def new
    #폼헬퍼 쓰기위한 코드
    @club = Club.new
    # binding.pry
  end

  def create
    @club = Club.new(club_params)
    # binding.pry
    @club.save
    redirect_to @club
  end

  def show
    @club_articles = @club.articles
  end

  def edit
  end

  def update
    @club.update(club_params)
    redirect_to @club
  end

  def destroy
    @club.destroy
    redirect_to club_index_path
  end



  private

    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(:name, :content, :category, :mainimage)
    end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to Club.find(Article.find(@comment.article_id).club_id)
  end

  def destroy
    @comment = Comment.find(params[:id])

    if check_user == true

      @comment.destroy
      redirect_to Club.find(Article.find(@comment.article_id).club_id)

    #로그인하지 않은 경우
    elsif current_user == nil
      #TODO: 로그인 후 이용해주세요 알람창 뜨게하기 자바스크립트로 해야함
      redirect_to 'users/sign-in'

    # 본인 댓글이 아닐경우
    else
      #TODO: 본인댓글만 삭제할 수 있습니다. 알람창 뜨게하기 자바스크립트로 해야함
      redirect_to :back
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :article_id, :user_id)
    end

    def check_user
      if User.find(@comment.user_id) == current_user
        return true
      else
        return false
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController





end

app/controllers/interest_controller.rb
class InterestController < ApplicationController
    def interest
        @interest = Interest.new()
        @interest.club_id = params[:c_id]
        @interest.save
        redirect_to '/users/show'
    end
    
    def cancel
    end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :send_form]
  
  def send_form
    @reciever_id = params[:id]
  end

  def create
    @message = Message.new(message_params)
    @message.save
    redirect_to '/users/show'
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to '/users/show'
  end

  private
    def message_params
      params.require(:message).permit(:content, :user_id, :reciever_id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # @user = User.find(params[:id])
     @user_email = current_user.email
     @user_name = current_user.name
     @user_major = current_user.major
     @user_student_id = current_user.student_id
     
     @user_comments = current_user.comments
     @user_articles = current_user.articles
  end
  
  def messages
     @user_messages = current_user.messages
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/article/edit.html.erb
<!--수정 모달에 들어갈 부분-->
<div class="modal-header">
  <h4>게시글 수정</h4>
  <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>

<div class="modal-body">
  <%= form_for(@article) do |a| %>
  
    <%= a.label :title %>
    <%= a.text_field :title, placeholder: '제목을 입력해주세요' %>
  
    <%= a.label :content %>
    <%= a.text_area :content %>
  
    <%= a.hidden_field :club_id %>
  
    <% @article.images.each do |i| %>
      <%= image_tag(i) %>
    <% end %>
  
    <%= a.label :images %>
    <%= a.file_field :images, multiple: true %>
</div>

<div class="modal-footer">
  <%= a.submit value: '얍!' %>
  <% end %>
</div>

app/views/club/_form.html.erb
<% #TODO: 폼헬퍼 만들기 %>
<%= form_for(@club) do |c| %>

  <%= c.label :name %>
  <%= c.text_field :name, placeholder: '제목을 입력해주세요', class: 'hack' %>

  <%= c.label :content %>
  <%= c.text_area :content %>

  <%= c.label :categoty %>
  <%= c.text_area :category %>

  <%= c.label :mainimage %>
  <%= c.file_field :mainimage %>

  <%= c.submit value: '얍!' %>

<% end %>

app/views/club/edit.html.erb
<div class = 'container club_edit'>
  
    <h1>동아리 수정</h1>
  
  <%= form_for(@club) do |c| %>
  
    <h6>동아리 명</h6>
    <%= c.text_field :name, placeholder: '제목을 입력해주세요', class: 'hack' %>
    
    <h6>동아리 설명</h6>
    <%= c.text_area :content %>
  
    <h6>동아리 분류</h6>
    <%= c.text_area :category %>
  
    <h6>동아리 사진</h6>
    <%= c.file_field :mainimage %>
  
    <%= c.submit value: '수정' %>
  
  <% end %>
  
  
  <!--<p><#%= #link_to 'index', club_index_path %></p>-->
</div>

app/views/club/index.html.erb
<script>
function category_filter(category_name){
  var category_list = document.getElementsByClassName("dong-li-category");
  for (i = 0; i < category_list.length; i++) {
    if (category_list[i].innerHTML.indexOf(category_name) > -1) {
      category_list[i].parentElement.parentElement.style.display = "";
    } else {
      category_list[i].parentElement.parentElement.style.display = "none";
    }
  }
}
</script>  

<div class = 'dongari-wrap'>
        
        <!--동아리 캐러셀-->
        <div id="dongari-car" class="carousel slide" data-ride="carousel">
        
          <!-- 캐러셀 이미지 -->
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%=image_tag("Carouselimage1.jpg")%>
            </div>
            <div class="carousel-item">
              <%=image_tag("Carouselimage2.jpg")%>
            </div>
            <div class="carousel-item">
              <%=image_tag("carouselimage3.jpg")%>
            </div>
          </div>
        
          <!-- 좌우 화살표 -->
          <a class="carousel-control-prev" href="#dongari-car" data-slide="prev">
            <i class="fas fa-caret-left fa-4x"></i>
          </a>
          <a class="carousel-control-next" href="#dongari-car" data-slide="next">
            <i class ="fas fa-caret-right fa-4x"></i>
          </a>
        </div>
        
        <div class = 'category_name'>
          <h1 style='margin-bottom: 0'>동아리 분류</h1>
        </div>
        <!--동아리 카테고리-->
        <div class="dongari-cat-wrap">
          <div class="dong-categories">
              <a><div class="dong-cat-list" onclick = "category_filter('예술')";><p>예   술</p>
                <%=image_tag("예술.jpg", :style => "padding-left: 0;")%>
              </div></a>
              <a><div class="dong-cat-list" onclick = "category_filter('헬스')";><p>헬   스</p>
                <%=image_tag("헬스.jpg")%>
              </div></a>
              <a><div class="dong-cat-list" onclick = "category_filter('봉사')";><p>봉   사</p>
                <%=image_tag("봉사.jpg")%>
              </div></a>
              <a><div class="dong-cat-list" onclick = "category_filter('종교')";><p>종   교</p>
                <%=image_tag("종교2.jpg")%>
              </div></a>
              <a><div class="dong-cat-list" onclick = "category_filter('학술')";><p>학   술</p>
                <%=image_tag("학술.jpg", :style => "padding-right: 0;")%>
              </div></a>
          </div> 
        </div>
    
    <div class='dong-list-wrap'>
        <%= link_to '동아리 작성', new_club_path, :class => 'club_create' %>
        
        <ul class='dong-list'>
            <% @clubs.each do |club| %>
                <li>
                    <div class = 'dong-li-img'><%= link_to image_tag(club.mainimage), club %></div>
                    <div class = 'dong-li-sub'>
                    <a><%= link_to club.name, club %></a>
                    <p class = 'dong-li-category' style = "font-size: 15px;
                                margin-bottom: 2px;"><%= club.category %></p>
                    <p><%= club.content %></p>
                    </div>
                <!--이거 일단 주석처리 해놓고 show 부분으로 옮길지 고민중-->  
                    <%#= link_to 'Show', club %>
                    <%#= link_to 'Edit', edit_club_path(club) %>
                    <%#= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/club/new.html.erb
<div class = 'container club_write'>
  <h1>동아리 생성</h1>
  
  <%= form_tag "/club", method: "post", multipart: true do %>
    <input type = "hidden" value = '<%= form_authenticity_token%>' name ='authenticity_token'></input>
    <h6>동아리명</h6>
    <input type = "text" class = 'title' name = "club[name]"></input>
    <h6>동아리 설명</h6>
    <input type = "text" class = 'inform' name = "club[content]"></input>
    <h6>동아리 분류</h6>
    <select class = 'category' name = "club[category]">
      <option value="예술">예술</option>
      <option value="운동">운동</option>
      <option value="봉사">봉사</option>
      <option value="종교">종교</option>
      <option value="학술">학술</option>
    </select>
    <h6>동아리 사진</h6>
    <input type = "file" class = 'file' name = "club[mainimage]" %></input>
    <input type = "submit"></input>
  <% end %>
</div>

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/message/send_form.html.erb
<div class = 'message container'>
  <%= form_tag "/message/create", method: "post" do%>
    <input type = "hidden" value = '<%= form_authenticity_token%>' name ='authenticity_token'></input>
    <input type = "text" name = "message[content]" placeholder="쪽지 내용 입력"></input>
    <input type = "hidden" name = "message[user_id]" value = <%= current_user.id %>></input>
    <input type = "hidden" name = "message[reciever_id]" value = "<%= @reciever_id %>"></input>
    <input type = "submit" style = "margin-left: 5px;"></input>
  <% end %>
</div>

app/views/users/messages.html.erb
	<div class="container-login100">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">
			<form class="login100-form validate-form">
					<%= image_tag("postbox.png", :class => "banana_img" )%>
				<span class="login100-form-title p-b-37">
					쪽지함
				</span>

				<div class="wrap-input100 validate-input m-b-20">
					<p>보낸 쪽지 목록</p>
					<% @user_messages.each do |m| %>
					 		<span>쪽지 받는 사람 : </span> <%= User.find(m.reciever_id).name %>
						   	<span>쪽지 내용 : </span> <%= m.content %>
					   		<%= link_to "/message/destroy/" + m.id.to_s, method: :delete, data: { confirm: '쪽지를 삭제 하시겠습니까?' } do%>
					  			<span>쪽지 취소 버튼</span>
							<% end %>
									<br>
					<% end %>
				</div>
				
				<div class="wrap-input100 validate-input m-b-20">
					<p>받은 쪽지 목록</p>
					<% Message.all.each do |m| %>
						<% if m.reciever_id == current_user.id %>
							<span>보낸 사람 : </span> <%= User.find(m.user_id).name %>
							<span>쪽지 내용 : </span> <%= m.content %>
							<br>
						<% end %>
					<% end %>
				</div>

			</form>

			
		</div>
	</div>

app/views/users/show.html.erb
<!--<h1>마이페이지</h1>
<%= @user_email %> <br/>
<%= @user_student_id %> <br/>
<%= @user_major %> <br/>


<h2>지원현황</h2>
<br/>
<h2>즐겨찾기</h2>
<br/>

<h2>내가 작성한 글</h2>
<br/>
<h2>내가 작성한 댓글</h2>
    <% @user_comments.each do |c| %>
        <span>해당 게시글</span>
        <%= Article.find(c.article_id).content %>
        <%= c.content %>
        <br>
    <% end %>
<br/>

<%= link_to "회원정보수정", edit_user_registration_url %>

-->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>MyPage</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/mypage.css">
<!--===============================================================================================-->
</head>
<body>
	
	
	<div class="container-login100">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">
			<form class="login100-form validate-form">
				<%= image_tag("bananaplant.png", :class => "banana_img" )%>
				<span class="login100-form-title p-b-37">
					<%= @user_name %>
				</span>

				<div class="wrap-input100 validate-input m-b-20">
					<h4>국민대 웹메일</h4>	
					<p><%= @user_email %></p>  
				</div>
				
				<div class="wrap-input100 validate-input m-b-20">
					<h4>학번</h4>
					<p><%= @user_student_id %></p>    
				</div>
				
				<div class="wrap-input100 validate-input m-b-20">
					<h4>전공</h4>
					<p><%= @user_major %></p>
				</div>
	
				<!--<div class="wrap-input100 validate-input m-b-20">-->
				<!--	<h4>찜한 목록들</h4>-->
				<!--	<%# @user_interests.each do |i| %>-->
    <!--   					 	<span>찜한 동아리 이름 : </span> <%#= Club.find(i.club_id).name %>-->
    <!--   						<br>-->
    <!--				<%# end %>-->
				<!--</div>-->
				
				<% #TODO: 여기부터 디자인 수정필요%>
				<div class="wrap-input100 validate-input m-b-20">
    				<h4>자신이 쓴 게시글</h4>
    				<% @user_articles.each do |a| %>
       					 	<span>게시물 내용 : </span> <%= a.content %>
       					 	이미지는 일단 추가안함
       						<br>
    				<% end %>
    				<h4>자신이 쓴 댓글</h4>
    				<% @user_comments.each do |c| %>
       					 	<span>댓글 단 게시물 내용 : </span> <%= Article.find(c.article_id).content %>
       						<span>댓글 내용 : </span> <%= c.content %>
        					<br>
    				<% end %>
				</div>
	  				
				<div class="container-login100-form-btn">
					<button class="login100-form-btn">
						<%= link_to "회원정보수정", edit_user_registration_url %>
					</button>
				</div>
				
				<br/>
				
				<div class="container-login100-form-btn">
				  <a href = "/users/messages">
					<button class="login100-form-btn">
				      쪽지함
					</button>
				  </a>
				</div>
				
			</form>

			
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>